# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DISYSTEST' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for DISYS
  pod 'Alamofire', '~> 4.4'
  pod 'AlamofireImage', '~> 3.3'
  pod 'ObjectMapper', '~> 3.3'
  pod 'SwiftyJSON', '~> 3.1.4'
  pod 'MBProgressHUD', '~> 1.1.0'

  # Pods for DISYSTEST

  target 'DISYSTESTTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DISYSTESTUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
